### ISSUE TITLE
Where from I get the key ID?

### ISSUE THREAD

**Issue by Compro-Prasad** [kensanata/ggg#1]
https://github.com/kensanata/ggg/blob/f0b5dad57931994470fbfd5167f96a7696d2a9bd/gmail-gnus-gpg.el#L17

**Comment by Compro-Prasad** [comment]
Got it. For me it wasn't there where you showed in the README but instead was in the fingerprint(last 8 digits).

**Comment by kensanata** [comment]
OK. If anybody else has the same problem, I’ll check to see whether certain (newer?) versions of GPG use a different output format.

**Comment by Compro-Prasad** [comment]
11:35 : ~ $ gpg --version
gpg (GnuPG) 2.2.5
libgcrypt 1.8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/compro/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

**Comment by kensanata** [comment]
I have 2.2.4, here.

As for the document itself, the section on how to generate the key tells you how to identify it (search for "gpg --gen-key").

I guess we could explain how to run `gpg --list-secret-keys` to find it again.

Do you want to propose a change that would have helped in your situation?

**Comment by Compro-Prasad** [comment]
It would be better to say that **The key ID is the last 8 digits of your fingerprint** as the fingerprint will always be shown when we list the keys.

The command `gpg --list-secret-keys` only shows the encryption mechanism(*rsa2048*), the dates, my details and the fingerprint and not the key ID.

**Comment by kensanata** [comment]
That is so strange. From the README, here's some output when the key is generated:

```
pub   4096R/7893C0FD 2015-07-24 [expires: 2016-07-23]
      Key fingerprint = 1A38 75FD 21ED 85BE 5AC6  BF49 5C1A C924 7893 C0FD
```

And clearly 4096R/**7893C0FD** and 1A38 75FD 21ED 85BE 5AC6  BF49 5C1A C924 **7893 C0FD** refer to the same thing. I think I'll write something right there, expanding on the paragraph where it says "The first hex number is your Key ID. In this case that would be 7893C0FD. You'll need to remember that."
