### ISSUE TITLE
Got an Error

### ISSUE THREAD

**Issue by Compro-Prasad** [kensanata/ggg#2]
```
Opening connection to imap.gmail.com via tls...
nnimap (gmail) open error: ‘’.  Continue? (y or n) n
Couldn’t open server on gmail
```
From `*Messages*` buffer. Which part am I doing it wrong?

**Comment by kensanata** [comment]
That's the error I get when a server is offline, i.e. I think at the time you were unable to reach imap.gmail.com.

**Comment by Compro-Prasad** [comment]
I am on a 2G connection. Is that a problem? Does Gmail require good speed or is available only in some selected regions? Or could it be that the ISP is blocking my request to `imap.gmail.com`.

**Comment by kensanata** [comment]
I would say it's unrelated to TLS. Duckducking around I found [Test SSL / TLS with GnuTLS from the Command Line](https://scottlinux.com/2014/03/12/test-ssl-tls-with-gnutls-from-the-command-line/) which tests it using `gnutls-cli -d 5 imap.gmail.com -p 993` but when I try it I get a "Handshake has failed" error. But then I noticed in [GNU Emacs Gnus can't connect to gmail IMAP](https://unix.stackexchange.com/questions/272670/gnu-emacs-gnus-cant-connect-to-gmail-imap) where the answer says "You need to go to the website and enable connections from less secure apps." This links to [Let less secure apps use your account](https://support.google.com/accounts/answer/6010255). I'm not sure this is related because `gnutls-cli` doesn't actually log in, so who knows.

**Comment by kensanata** [comment]
Hah! I tried from a different machine and now it works:
```
$ gnutls-cli imap.gmail.com -p 993
Processed 174 CA certificate(s).
Resolving 'imap.gmail.com'...
Connecting to '2a00:1450:400c:c06::6c:993'...
- Certificate type: X.509
- Got a certificate list of 2 certificates.
- Certificate[0] info:
 - subject `C=US,ST=California,L=Mountain View,O=Google Inc,CN=imap.gmail.com', issuer `C=US,O=Google Trust Services,CN=Google Internet Authority G3', RSA key 2048 bits, signed using RSA-SHA256, activated `2018-02-20 15:10:02 UTC', expires `2018-05-15 14:10:00 UTC', SHA-1 fingerprint `af3a6aa30f69bb24273220b7485f17a51f38a018'
        Public Key ID:
                99263d1913528eaa484e42cf21955b40170ebffb
        Public key's random art:
                +--[ RSA 2048]----+
                |  .=ooo.o        |
                |  ..=. + .       |
                | o .oo. +        |
                |. +..... *       |
                |.o o... S        |
                |=. .  .o .       |
                |...  .           |
                |      .          |
                |       E         |
                +-----------------+

- Certificate[1] info:
 - subject `C=US,O=Google Trust Services,CN=Google Internet Authority G3', issuer `OU=GlobalSign Root CA - R2,O=GlobalSign,CN=GlobalSign', RSA key 2048 bits, signed using RSA-SHA256, activated `2017-06-15 00:00:42 UTC', expires `2021-12-15 00:00:42 UTC', SHA-1 fingerprint `eeacbd0cb452819577911e1e6203db262f84a318'
- Status: The certificate is trusted.
- Description: (TLS1.2)-(ECDHE-RSA-SECP256R1)-(AES-128-GCM)
- Session ID: 6F:9A:25:95:2D:C6:64:E7:13:8E:F4:D1:8F:84:BA:EB:69:12:AA:01:7A:B2:A7:F3:6B:20:A7:62:D2:EA:C6:AE
- Ephemeral EC Diffie-Hellman parameters
 - Using curve: SECP256R1
 - Curve size: 256 bits
- Version: TLS1.2
- Key Exchange: ECDHE-RSA
- Server Signature: RSA-SHA256
- Cipher: AES-128-GCM
- MAC: AEAD
- Compression: NULL
- Handshake was completed

- Simple Client Mode:

* OK Gimap ready for requests from 2a02:418:6050:ca7:ea75:b12d:1d:10 61mb413442314wrg
```
That's gnutls-cli 3.3.8.

**Comment by kensanata** [comment]
So now we have learned nothing new for your situation. You should try using a recent `gnutls-cli` to see whether the server is denying you. If that's the problem, maybe it is your 2G connection or some geoblocking or whatever. But if `gnutls-cli` works, then you need to figure our what TLS library Emacs is using.

**Comment by Compro-Prasad** [comment]
The output of `gnutls-cli imap.gmail.com -p 993` looks fine to me and it gives more verbose output than the one you showed here. That means it is working. Just that gnus is failing for some reason. As far as I can recall stuff on Linux generally depends on each other. So, GNU Emacs would be using the same TLS library as that of `gnutls`. Is there a way to test this thing using Emacs Lisp?

**Comment by Compro-Prasad** [comment]
I just found out `(open-gnutls-stream "tls" "tls-buffer" "imap.gmail.com" "imaps")` which creates buffer `tls-buffer` having:
```
* OK Gimap ready for requests from 2405:205:63a8:9f8a:c524:b3c2:f00e:49f4 z11mb373388085iod
```
Is it same for you too?
Source: https://www.gnu.org/software/emacs/manual/html_mono/emacs-gnutls.html

**Comment by Compro-Prasad** [comment]
`gnutls-cli imap.gmail.com -p 993` works for me. That means the service is available just that Emacs isn't able to connect to it.
To confirm, I only had changed the Email address and key ID after copying your `.gnus.el`. Is there anything else you would like to point me to change?

**Comment by kensanata** [comment]
Yeah, I also get the `tls-buffer`. I'm out of ideas, sadly.

**Comment by Compro-Prasad** [comment]
It is working now. I loaded my config with Emacs 27.0.50 and everything is running fine.

**Comment by kensanata** [comment]
Weird, but in a good way. :smiley:
