### ISSUE TITLE
Unable to successfully send message

### ISSUE THREAD

**Issue by Compro-Prasad** [kensanata/ggg#3]
I can write message from the `*Group*` buffer using `m` key but it doesn't send the body of the message. Only the subject and two attachments. One saying 1.0 and the other having a PGP key block.

**Comment by kensanata** [comment]
This isn't much information... When I open an encrypted mail I sent, I get to see some garbage and Emacs asks me: "Decrypt (PGP) part? (y or n)" and when I answer "n" then this is what I see:

```text
From: Facebook <noreply@facebookmail.com>
Subject: Encrypted Notification from Facebook [ARNqp-4uuL9Qqfwk]
To: Alex Schröder <alex@gnu.org>
Date: Fri, 2 Mar 2018 12:12:32 -0800 (23 hours, 49 minutes, 3 seconds ago)
Attachment: [1. application/pgp-encrypted]...

[1. application/pgp-encrypted]...

```

**Comment by Compro-Prasad** [comment]
Actually I can read everything in Emacs but not on Gmail.

**Comment by kensanata** [comment]
Cool! Problem solved, right?

**Comment by Compro-Prasad** [comment]
I want to see the body in GMail web interface too. How to achieve that?
Is there a way of signing the message with my private key and sending the message with my public key so that clients can decrypt it for the user to whom I have sent the Email?
Or how can I totally remove the encryption part? I just want to send an Email to a person who still lacks the knowledge of PGP.

**Comment by kensanata** [comment]
Not unless the client also has PGP or GPG integration which Gmail has not since that would require them to store your private key on their server. The recipient must download the email or copy and paste the encrypted part and read it locally.

**Comment by Compro-Prasad** [comment]
But I am unable to see any body.

**Comment by kensanata** [comment]
I think this goes beyond the topic of Gmail, Gnus and GPG. Download the mail, save the attachments, something like that? When I open an encrypted mail I receive, it looks straight forward:

![image](https://user-images.githubusercontent.com/1145712/36948979-b278eb0c-1fe2-11e8-8aee-ee60f5dffd4a.png)

When I look at an email I sent myself, it looks worse:

![image](https://user-images.githubusercontent.com/1145712/36949017-26ff8490-1fe3-11e8-82d3-42c24e842b1e.png)

But I can download the second noname attachment:

![image](https://user-images.githubusercontent.com/1145712/36949033-5740aa8a-1fe3-11e8-8b50-831caeedfec5.png)

And then I can use `C-x h M-x epa-decrypt-armor-in-region` to read it.
Or use `M-x epa-decrypt-file` I guess.

**Comment by Compro-Prasad** [comment]
Okay, so I can read my own Email. But what about the receiver? He/She doesn't have my private key. Though I have seen people signing their mail and their PGP signature is always sent with their attachment. Is this a property of their own mail server?
![screenshot from 2018-03-05 00-17-27](https://user-images.githubusercontent.com/11143962/36949192-0130fb54-200b-11e8-8560-4caad9d4ff6d.png)

**Comment by kensanata** [comment]
I don't think I want my how-to to expand to a whole explanation of public key cryptography works, so here's just a short intro:

- "encrypting" means using a copy of the public key of the recipient, which you must have received via some channel. such that they can decrypt the message using their secret key (you must get a copy of their public key before doing it)

- "signing" means using your secret key to encrypt a copy (or a hash or a compressed version) of your document which nobody can read, but recipients can use their copy of your public key to verify that they get the same result (now they must have gotten a copy of your public key before doing it)

Doing this automatically requires GPG integration of the email client (which is what Gnus has), or you need to do it manually using gpg from the command line.

Further reading:
* [Encrypting and decrypting documents](https://www.gnupg.org/gph/en/manual/x110.html)
* [Making and verifying signatures](https://www.gnupg.org/gph/en/manual/x135.html)

**Comment by Trevoke** [comment]
I think the link in the first paragraph explains it pretty well, honestly: https://emailselfdefense.fsf.org/en/

@Compro-Prasad does this link not answer your questions?

**Comment by kensanata** [comment]
@Trevoke I should definitely link that article.

**Comment by kensanata** [comment]
D'oh, I already do.
