### ISSUE TITLE
Sign instead of Encrypt

### ISSUE THREAD

**Issue by Compro-Prasad** [kensanata/ggg#4]
AFAIK emails I have seen were signed and almost none of them were encrypted. Mail clients like Gmail support decrypting of encrypted messages? For a new user like me I would like to see my test message as it is. Not as an attachment that I might have to decrypt. Sure, you can provide an option to even encrypt the message but default should be to sign off. Opinions?

**Comment by kensanata** [comment]
In my personal communications, signing without encryption keeps no secrets and takes away the possibility of repudiation, thus it only ever helps my adversaries. This is different in official communications, signing of releases and other such things. But in my email client I only ever need encryption.
You can use Gnus to do what you want, though.
http://www.gnus.org/manual/message_20.html#Signing-and-encryption
