### ISSUE TITLE
How to read all my read emails in gnus?

### ISSUE THREAD

**Issue by Compro-Prasad** [kensanata/ggg#5]
Not an issue. But just a question.

**Comment by kensanata** [comment]
“If there are no unread articles in the group, or if you give a non-numerical prefix to this command, Gnus will offer to fetch all the old articles in this group from the server. If you give a numerical prefix n, n determines the number of articles Gnus will fetch. If n is positive, Gnus fetches the n newest articles, if n is negative, Gnus fetches the abs(n) oldest articles.”
http://www.gnus.org/manual/gnus_14.html#Selecting-a-Group
